-- Cấu hình định dạng ngày tháng để Insert dễ dàng hơn
ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS';
ALTER SESSION SET NLS_TIMESTAMP_FORMAT = 'YYYY-MM-DD HH24:MI:SS.FF';

-------------------------------------------------------------------
-- PHẦN 1: XÓA BẢNG CŨ (NẾU CÓ) ĐỂ LÀM SẠCH DATABASE
-------------------------------------------------------------------
BEGIN
FOR t IN (SELECT table_name FROM user_tables) LOOP
    EXECUTE IMMEDIATE 'DROP TABLE "' || t.table_name || '" CASCADE CONSTRAINTS';
END LOOP;
END;
/

-------------------------------------------------------------------
-- PHẦN 2: TẠO BẢNG (DDL) - KHÔNG RÀNG BUỘC KHÓA NGOẠI
-------------------------------------------------------------------

CREATE TABLE mau_sac (
                         id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                         ten NVARCHAR2(256),
                         ma_mau_sac NVARCHAR2(256),
                         ngay_tao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                         ngay_sua TIMESTAMP,
                         nguoi_tao NUMBER(19),
                         nguoi_sua NUMBER(19),
                         trang_thai NUMBER(1,0) DEFAULT 1
);

CREATE TABLE chat_lieu (
                           id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                           ten NVARCHAR2(256),
                           ngay_tao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                           ngay_sua TIMESTAMP,
                           nguoi_tao NUMBER(19),
                           nguoi_sua NUMBER(19),
                           trang_thai NUMBER(1,0) DEFAULT 1
);

CREATE TABLE kich_co (
                         id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                         ten NVARCHAR2(256),
                         ngay_tao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                         ngay_sua TIMESTAMP,
                         nguoi_tao NUMBER(19),
                         nguoi_sua NUMBER(19),
                         trang_thai NUMBER(1,0) DEFAULT 1
);

CREATE TABLE thuong_hieu (
                             id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                             ten NVARCHAR2(256),
                             ngay_tao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                             ngay_sua TIMESTAMP,
                             nguoi_tao NUMBER(19),
                             nguoi_sua NUMBER(19),
                             trang_thai NUMBER(1,0) DEFAULT 1
);

CREATE TABLE the_loai (
                          id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                          ten NVARCHAR2(256),
                          ngay_tao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                          ngay_sua TIMESTAMP,
                          nguoi_tao NUMBER(19),
                          nguoi_sua NUMBER(19),
                          trang_thai NUMBER(1,0) DEFAULT 1
);

CREATE TABLE de_giay (
                         id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                         ten NVARCHAR2(256),
                         ngay_tao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                         ngay_sua TIMESTAMP,
                         nguoi_tao NUMBER(19),
                         nguoi_sua NUMBER(19),
                         trang_thai NUMBER(1,0) DEFAULT 1
);

CREATE TABLE mui_giay (
                          id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                          ten NVARCHAR2(256),
                          ngay_tao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                          ngay_sua TIMESTAMP,
                          nguoi_tao NUMBER(19),
                          nguoi_sua NUMBER(19),
                          trang_thai NUMBER(1,0) DEFAULT 1
);

CREATE TABLE co_giay (
                         id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                         ten NVARCHAR2(256),
                         ngay_tao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                         ngay_sua TIMESTAMP,
                         nguoi_tao NUMBER(19),
                         nguoi_sua NUMBER(19),
                         trang_thai NUMBER(1,0) DEFAULT 1
);

CREATE TABLE san_pham (
                          id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                          id_thuong_hieu NUMBER(19),
                          id_the_loai NUMBER(19),
                          ten NVARCHAR2(256),
                          ngay_tao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                          ngay_sua TIMESTAMP,
                          nguoi_tao NUMBER(19),
                          nguoi_sua NUMBER(19),
                          trang_thai NUMBER(1,0) DEFAULT 1,
                          mo_ta NCLOB
);

-- Bảng USER phải để trong ngoặc kép vì trùng từ khóa Oracle
CREATE TABLE "USER" (
                        id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                        email NVARCHAR2(256),
                        password NVARCHAR2(2000),
                        role NVARCHAR2(256),
                        id_khach_hang NUMBER(19),
                        id_nhan_vien NUMBER(19),
                        verify_at TIMESTAMP,
                        avatar NVARCHAR2(256),
                        ngay_tao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        ngay_sua TIMESTAMP,
                        nguoi_tao NUMBER(19),
                        nguoi_sua NUMBER(19),
                        trang_thai NUMBER(1,0) DEFAULT 1
);

CREATE TABLE anh (
                     id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                     id_san_pham NUMBER(19),
                     url NVARCHAR2(500),
                     main NUMBER(1,0) DEFAULT 0,
                     ngay_tao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                     ngay_sua TIMESTAMP,
                     nguoi_tao NUMBER(19),
                     nguoi_sua NUMBER(19),
                     trang_thai NUMBER(1,0) DEFAULT 1
);

CREATE TABLE chi_tiet_san_pham (
                                   id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                                   id_san_pham NUMBER(19),
                                   id_mau_sac NUMBER(19),
                                   id_de_giay NUMBER(19),
                                   id_kich_co NUMBER(19),
                                   id_chat_lieu NUMBER(19),
                                   id_co_giay NUMBER(19),
                                   id_anh NUMBER(19),
                                   id_mui_giay NUMBER(19),
                                   ma_san_pham NVARCHAR2(256),
                                   gia_nhap NUMBER(11,2),
                                   gia_goc NUMBER(11,2),
                                   gia_ban NUMBER(11,2),
                                   is_sale NUMBER(1,0) DEFAULT 0,
                                   giam_phan_tram NUMBER(10,0) DEFAULT 0,
                                   giam_tien NUMBER(11,2),
                                   so_luong_ton NUMBER(10,0),
                                   ngay_tao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                   ngay_sua TIMESTAMP,
                                   nguoi_tao NUMBER(19),
                                   nguoi_sua NUMBER(19),
                                   trang_thai NUMBER(1,0) DEFAULT 1
);

CREATE TABLE khach_hang (
                            id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                            ma_khach_hang NVARCHAR2(256),
                            ho_ten NVARCHAR2(256),
                            gioi_tinh NUMBER(1,0),
                            ngay_sinh DATE,
                            sdt VARCHAR2(15),
                            diem NUMBER(10,0),
                            id_hang_khach_hang NUMBER(19),
                            dia_chi_mac_dinh NUMBER(19),
                            ngay_tao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                            ngay_sua TIMESTAMP,
                            nguoi_tao NUMBER(19),
                            nguoi_sua NUMBER(19),
                            trang_thai NUMBER(1,0) DEFAULT 1
);

CREATE TABLE dia_chi (
                         id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                         id_khach_hang NUMBER(19),
                         so_nha NVARCHAR2(256),
                         phuong_xa NVARCHAR2(256),
                         quan_huyen NVARCHAR2(256),
                         tinh_thanh_pho NVARCHAR2(256),
                         ngay_tao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                         ngay_sua TIMESTAMP,
                         nguoi_tao NUMBER(19),
                         nguoi_sua NUMBER(19),
                         trang_thai NUMBER(1,0) DEFAULT 1
);

CREATE TABLE hoa_don (
                         id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                         ma_hoa_don NVARCHAR2(256),
                         ten_nguoi_nhan NVARCHAR2(256),
                         ma_van_chuyen NVARCHAR2(256),
                         email_nguoi_nhan NVARCHAR2(256),
                         so_tien_can_thanh_toan NUMBER(11,2) DEFAULT 0.00,
                         so_tien_da_thanh_toan NUMBER(11,2),
                         loai_hoa_don NUMBER(1,0),
                         id_nhan_vien NUMBER(19),
                         id_khach_hang NUMBER(19),
                         id_voucher NUMBER(19),
                         id_don_vi_van_chuyen NUMBER(19),
                         tong_tien NUMBER(11,2),
                         giam_gia NUMBER(11,2),
                         thuc_thu NUMBER(11,2),
                         phi_ship NUMBER(11,2),
                         ngay_xac_nhan TIMESTAMP,
                         ngay_ship TIMESTAMP,
                         ngay_nhan TIMESTAMP,
                         sdt_nhan VARCHAR2(15),
                         dia_chi_nhan NVARCHAR2(256),
                         ngay_tao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                         ngay_sua TIMESTAMP,
                         nguoi_tao NUMBER(19),
                         nguoi_sua NUMBER(19),
                         trang_thai NVARCHAR2(50),
                         hinh_thuc_thanh_toan NVARCHAR2(256)
);

CREATE TABLE hoa_don_chi_tiet (
                                  id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                                  id_hoa_don NUMBER(19),
                                  id_chi_tiet_san_pham NUMBER(19),
                                  gia_goc NUMBER(11,2),
                                  gia_ban NUMBER(11,2),
                                  so_luong NUMBER(10,0)
);

CREATE TABLE gio_hang (
                          id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                          id_khach_hang NUMBER(19),
                          ngay_tao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                          ngay_sua TIMESTAMP,
                          nguoi_tao NUMBER(19),
                          nguoi_sua NUMBER(19),
                          trang_thai NUMBER(1,0) DEFAULT 1
);

CREATE TABLE gio_hang_chi_tiet (
                                   id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                                   id_gio_hang NUMBER(19),
                                   id_chi_tiet_san_pham NUMBER(19),
                                   so_luong NUMBER(10,0),
                                   ngay_tao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                   ngay_sua TIMESTAMP,
                                   trang_thai NUMBER(1,0) DEFAULT 1
);

CREATE TABLE chuc_vu (
                         id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                         ten NVARCHAR2(256),
                         ngay_tao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                         ngay_sua TIMESTAMP,
                         nguoi_tao NUMBER(19),
                         nguoi_sua NUMBER(19),
                         trang_thai NUMBER(1,0) DEFAULT 1
);

CREATE TABLE nhan_vien (
                           id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                           ma_nhan_vien NVARCHAR2(256),
                           id_chuc_vu NUMBER(19),
                           ho_ten NVARCHAR2(256),
                           gioi_tinh NUMBER(1,0),
                           ngay_sinh DATE,
                           so_nha NVARCHAR2(256),
                           phuong_xa NVARCHAR2(256),
                           quan_huyen NVARCHAR2(256),
                           tinh_thanh_pho NVARCHAR2(256),
                           sdt VARCHAR2(15),
                           cccd VARCHAR2(20),
                           ngay_tao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                           ngay_sua TIMESTAMP,
                           nguoi_tao NUMBER(19),
                           nguoi_sua NUMBER(19),
                           trang_thai NUMBER(1,0) DEFAULT 1
);

CREATE TABLE voucher (
                         id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                         ma NVARCHAR2(256),
                         ten NVARCHAR2(256),
                         gia_tri_tien_mat NUMBER(11,2),
                         gia_tri_phan_tram NUMBER(10,0),
                         gia_tri_toi_da NUMBER(11,2),
                         id_hang_khach_hang NUMBER(19),
                         gia_tri_toi_thieu NUMBER(11,2),
                         so_luong NUMBER(10,0),
                         loai_voucher NVARCHAR2(256),
                         ngay_bat_dau TIMESTAMP,
                         ngay_ket_thuc TIMESTAMP,
                         ngay_tao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                         ngay_sua TIMESTAMP,
                         nguoi_tao NUMBER(19),
                         nguoi_sua NUMBER(19),
                         trang_thai NUMBER(10,0) DEFAULT 1,
                         mo_ta NVARCHAR2(256)
);

CREATE TABLE voucher_khach_hang (
                                    id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                                    id_khach_hang NUMBER(19),
                                    id_voucher NUMBER(19),
                                    ngay_tao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                    ngay_sua TIMESTAMP,
                                    nguoi_tao NUMBER(19),
                                    nguoi_sua NUMBER(19),
                                    trang_thai NUMBER(1,0) DEFAULT 1
);

CREATE TABLE hang_khach_hang (
                                 id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                                 ten NVARCHAR2(256),
                                 diem_toi_thieu NUMBER(10,0)
);

CREATE TABLE don_vi_van_chuyen (
                                   id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                                   ma_don_vi NVARCHAR2(256),
                                   ten_don_vi NVARCHAR2(256),
                                   dia_chi NVARCHAR2(256),
                                   api CLOB,
                                   token_api NVARCHAR2(999),
                                   ngay_tao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                   ngay_sua TIMESTAMP,
                                   nguoi_tao NUMBER(19),
                                   nguoi_sua NUMBER(19),
                                   trang_thai NUMBER(1,0) DEFAULT 1,
                                   CONSTRAINT check_json_api CHECK (api IS JSON)
);

CREATE TABLE hinh_thuc_thanh_toan (
                                      id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                                      ma_giao_dich NVARCHAR2(256),
                                      id_hoa_don NUMBER(19),
                                      hinh_thuc NVARCHAR2(256),
                                      tien_thanh_toan NUMBER(11,2),
                                      tien_thua NUMBER(11,2),
                                      mo_ta NVARCHAR2(256),
                                      ngay_tao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                      ngay_sua TIMESTAMP,
                                      nguoi_tao NUMBER(19),
                                      nguoi_sua NUMBER(19),
                                      trang_thai NUMBER(1,0) DEFAULT 1
);

CREATE TABLE lich_su_hoa_don (
                                 id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                                 id_hoa_don NUMBER(19),
                                 hanh_dong NVARCHAR2(256),
                                 thoi_gian TIMESTAMP,
                                 nguoi_thuc_hien NUMBER(19),
                                 trang_thai_sau_update NVARCHAR2(256)
);

CREATE TABLE notification (
                              id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                              created_by NVARCHAR2(256),
                              created_time NVARCHAR2(20),
                              title NVARCHAR2(256),
                              description NVARCHAR2(256),
                              creator_avatar_url NVARCHAR2(1000)
);

CREATE TABLE quan_tri (
                          id NUMBER(19) DEFAULT 1 PRIMARY KEY,
                          banner1 NVARCHAR2(256),
                          title1 NVARCHAR2(256),
                          mo_ta1 NVARCHAR2(256),
                          banner2 NVARCHAR2(256),
                          title2 NVARCHAR2(256),
                          mo_ta2 NVARCHAR2(256),
                          san_pham1 NUMBER(19),
                          title_sp1 NVARCHAR2(256),
                          san_pham2 NUMBER(19),
                          title_sp2 NVARCHAR2(256),
                          san_pham3 NUMBER(19),
                          title_sp3 NVARCHAR2(256),
                          san_pham_sale NUMBER(19),
                          title_sp_sale NVARCHAR2(256),
                          thoi_gian_sale TIMESTAMP
);

CREATE TABLE tags (
                      id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                      ten NVARCHAR2(256),
                      ngay_tao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                      ngay_sua TIMESTAMP,
                      nguoi_tao NUMBER(19),
                      nguoi_sua NUMBER(19),
                      trang_thai NUMBER(1,0) DEFAULT 1
);

CREATE TABLE tags_san_pham (
                               id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                               id_tag NUMBER(19),
                               id_san_pham NUMBER(19)
);

-------------------------------------------------------------------
-- PHẦN 3: INSERT DỮ LIỆU MẪU (DML) - 5 DÒNG MỖI BẢNG
-------------------------------------------------------------------

-- 1. MAU_SAC
INSERT INTO mau_sac (ten, ma_mau_sac, ngay_tao, trang_thai) VALUES ('Màu Đen', '#000000', TIMESTAMP '2024-02-05 02:17:10', 1);
INSERT INTO mau_sac (ten, ma_mau_sac, ngay_tao, trang_thai) VALUES ('Màu Trắng', '#FFFFFF', TIMESTAMP '2024-02-05 02:17:21', 1);
INSERT INTO mau_sac (ten, ma_mau_sac, ngay_tao, trang_thai) VALUES ('Màu Vàng', '#66FF00', TIMESTAMP '2024-02-05 03:02:34', 1);
INSERT INTO mau_sac (ten, ma_mau_sac, ngay_tao, trang_thai) VALUES ('Màu Đỏ', '#FF0000', TIMESTAMP '2024-02-13 10:35:40', 1);
INSERT INTO mau_sac (ten, ma_mau_sac, ngay_tao, trang_thai) VALUES ('Xanh Rêu', '#312A92', TIMESTAMP '2025-03-22 00:50:29', 1);

-- 2. CHAT_LIEU
INSERT INTO chat_lieu (ten, ngay_tao, trang_thai) VALUES ('Vải', TIMESTAMP '2024-02-05 02:15:55', 1);
INSERT INTO chat_lieu (ten, ngay_tao, trang_thai) VALUES ('Da Công Nghiệp', TIMESTAMP '2024-02-05 08:15:23', 1);
INSERT INTO chat_lieu (ten, ngay_tao, trang_thai) VALUES ('Da Lộn', TIMESTAMP '2024-02-14 07:53:49', 1);
INSERT INTO chat_lieu (ten, ngay_tao, trang_thai) VALUES ('Da Bò', TIMESTAMP '2024-04-14 14:20:16', 1);
INSERT INTO chat_lieu (ten, ngay_tao, trang_thai) VALUES ('Da Hữu Cơ', TIMESTAMP '2024-04-14 14:42:56', 1);

-- 3. KICH_CO
INSERT INTO kich_co (ten, ngay_tao, trang_thai) VALUES ('36', TIMESTAMP '2024-02-05 02:18:30', 1);
INSERT INTO kich_co (ten, ngay_tao, trang_thai) VALUES ('37', TIMESTAMP '2024-02-05 02:18:33', 1);
INSERT INTO kich_co (ten, ngay_tao, trang_thai) VALUES ('38', TIMESTAMP '2024-02-05 02:18:36', 1);
INSERT INTO kich_co (ten, ngay_tao, trang_thai) VALUES ('39', TIMESTAMP '2024-02-05 02:18:38', 1);
INSERT INTO kich_co (ten, ngay_tao, trang_thai) VALUES ('40', TIMESTAMP '2024-02-05 02:18:43', 1);

-- 4. THUONG_HIEU
INSERT INTO thuong_hieu (ten, ngay_tao, trang_thai) VALUES ('Converse', TIMESTAMP '2024-02-05 02:15:47', 1);
INSERT INTO thuong_hieu (ten, ngay_tao, trang_thai) VALUES ('Puma', TIMESTAMP '2024-02-05 08:14:58', 1);
INSERT INTO thuong_hieu (ten, ngay_tao, trang_thai) VALUES ('Nike', TIMESTAMP '2024-02-13 08:11:18', 1);
INSERT INTO thuong_hieu (ten, ngay_tao, trang_thai) VALUES ('Vans', TIMESTAMP '2024-02-14 07:53:29', 1);
INSERT INTO thuong_hieu (ten, ngay_tao, trang_thai) VALUES ('Adidas', TIMESTAMP '2024-02-22 14:53:20', 1);

-- 5. THE_LOAI
INSERT INTO the_loai (ten, ngay_tao, trang_thai) VALUES ('Chạy Bộ', TIMESTAMP '2024-02-05 02:13:36', 1);
INSERT INTO the_loai (ten, ngay_tao, trang_thai) VALUES ('Thể Thao', TIMESTAMP '2024-02-14 07:33:40', 1);
INSERT INTO the_loai (ten, ngay_tao, trang_thai) VALUES ('Thời Trang', TIMESTAMP '2024-02-20 04:30:12', 1);
INSERT INTO the_loai (ten, ngay_tao, trang_thai) VALUES ('Chạy Chậm', TIMESTAMP '2024-04-15 15:38:30', 1);
INSERT INTO the_loai (ten, ngay_tao, trang_thai) VALUES ('Leo Núi', TIMESTAMP '2024-05-01 10:00:00', 1);

-- 6. DE_GIAY
INSERT INTO de_giay (ten, ngay_tao, trang_thai) VALUES ('Cao Su', TIMESTAMP '2024-02-05 02:16:04', 1);
INSERT INTO de_giay (ten, ngay_tao, trang_thai) VALUES ('Đế Da', TIMESTAMP '2024-02-20 01:45:21', 1);
INSERT INTO de_giay (ten, ngay_tao, trang_thai) VALUES ('Đế Nhựa', TIMESTAMP '2024-03-01 08:00:00', 1);
INSERT INTO de_giay (ten, ngay_tao, trang_thai) VALUES ('Đế Foam', TIMESTAMP '2024-03-02 09:00:00', 1);
INSERT INTO de_giay (ten, ngay_tao, trang_thai) VALUES ('Đế Gỗ', TIMESTAMP '2024-03-03 10:00:00', 1);

-- 7. MUI_GIAY
INSERT INTO mui_giay (ten, ngay_tao, trang_thai) VALUES ('Mũi Nhọn', TIMESTAMP '2024-02-05 02:16:19', 1);
INSERT INTO mui_giay (ten, ngay_tao, trang_thai) VALUES ('Mũi Tròn', TIMESTAMP '2024-02-05 08:15:42', 1);
INSERT INTO mui_giay (ten, ngay_tao, trang_thai) VALUES ('Mũi Vuông', TIMESTAMP '2024-03-10 07:00:00', 1);
INSERT INTO mui_giay (ten, ngay_tao, trang_thai) VALUES ('Mũi Hở', TIMESTAMP '2024-03-11 08:00:00', 1);
INSERT INTO mui_giay (ten, ngay_tao, trang_thai) VALUES ('Mũi Bệt', TIMESTAMP '2024-03-12 09:00:00', 1);

-- 8. CO_GIAY
INSERT INTO co_giay (ten, ngay_tao, trang_thai) VALUES ('Cổ Cao', TIMESTAMP '2024-02-05 02:16:11', 1);
INSERT INTO co_giay (ten, ngay_tao, trang_thai) VALUES ('Cổ Thấp', TIMESTAMP '2024-02-05 08:15:35', 1);
INSERT INTO co_giay (ten, ngay_tao, trang_thai) VALUES ('Cổ Vừa', TIMESTAMP '2024-02-13 08:11:35', 1);
INSERT INTO co_giay (ten, ngay_tao, trang_thai) VALUES ('Không Cổ', TIMESTAMP '2024-03-01 07:00:00', 1);
INSERT INTO co_giay (ten, ngay_tao, trang_thai) VALUES ('Cổ Lửng', TIMESTAMP '2024-03-02 08:00:00', 1);

-- 9. SAN_PHAM
INSERT INTO san_pham (id, ten, mo_ta, trang_thai) VALUES (1, 'Chuck 70 AT-CX', '<p>Giày Converse cổ điển</p>', 1);
INSERT INTO san_pham (id, ten, mo_ta, trang_thai) VALUES (3, 'Air Jordan 1 Low', '<p>Phiên bản Air Jordan 1 cổ thấp</p>', 1);
INSERT INTO san_pham (id, ten, mo_ta, trang_thai) VALUES (4, 'Jordan Max Aura 5', '<p>Giày bóng rổ</p>', 1);
INSERT INTO san_pham (id, ten, mo_ta, trang_thai) VALUES (5, 'Nike Full Force Low White', '<p>Phong cách old-school</p>', 1);
INSERT INTO san_pham (id, ten, mo_ta, trang_thai) VALUES (6, 'Vans Style 36', '<p>Màu trắng ngà</p>', 1);

-- 10. USER
INSERT INTO "USER" (email, role, trang_thai) VALUES ('admin@gmail.com', 'ADMIN', 1);
INSERT INTO "USER" (email, role, trang_thai) VALUES ('staff@gmail.com', 'STAFF', 1);
INSERT INTO "USER" (email, role, trang_thai) VALUES ('customer1@gmail.com', 'CUSTOMER', 1);
INSERT INTO "USER" (email, role, trang_thai) VALUES ('customer2@gmail.com', 'CUSTOMER', 1);
INSERT INTO "USER" (email, role, trang_thai) VALUES ('manager@gmail.com', 'MANAGER', 1);

-- 11. ANH
INSERT INTO anh (url, main, trang_thai) VALUES ('https://img1.com', 1, 1);
INSERT INTO anh (url, main, trang_thai) VALUES ('https://img2.com', 0, 1);
INSERT INTO anh (url, main, trang_thai) VALUES ('https://img3.com', 0, 1);
INSERT INTO anh (url, main, trang_thai) VALUES ('https://img4.com', 0, 1);
INSERT INTO anh (url, main, trang_thai) VALUES ('https://img5.com', 1, 1);

-- 12. CHI_TIET_SAN_PHAM
INSERT INTO chi_tiet_san_pham (ma_san_pham, gia_ban, so_luong_ton, trang_thai) VALUES ('SP0001', 1299000, 77, 1);
INSERT INTO chi_tiet_san_pham (ma_san_pham, gia_ban, so_luong_ton, trang_thai) VALUES ('SP0002', 1999000, 67, 1);
INSERT INTO chi_tiet_san_pham (ma_san_pham, gia_ban, so_luong_ton, trang_thai) VALUES ('SP0003', 1499000, 24, 1);
INSERT INTO chi_tiet_san_pham (ma_san_pham, gia_ban, so_luong_ton, trang_thai) VALUES ('SP0004', 1399000, 99, 1);
INSERT INTO chi_tiet_san_pham (ma_san_pham, gia_ban, so_luong_ton, trang_thai) VALUES ('SP0005', 499000, 97, 1);

-- 13. KHACH_HANG
INSERT INTO khach_hang (ma_khach_hang, ho_ten, sdt, trang_thai) VALUES ('KH001', 'Nguyễn Văn A', '0987654321', 1);
INSERT INTO khach_hang (ma_khach_hang, ho_ten, sdt, trang_thai) VALUES ('KH002', 'Trần Thị B', '0987654322', 1);
INSERT INTO khach_hang (ma_khach_hang, ho_ten, sdt, trang_thai) VALUES ('KH003', 'Lê Văn C', '0987654323', 1);
INSERT INTO khach_hang (ma_khach_hang, ho_ten, sdt, trang_thai) VALUES ('KH004', 'Phạm Thị D', '0987654324', 1);
INSERT INTO khach_hang (ma_khach_hang, ho_ten, sdt, trang_thai) VALUES ('KH005', 'Hoàng Văn E', '0987654325', 1);

-- 14. DIA_CHI
INSERT INTO dia_chi (so_nha, quan_huyen, tinh_thanh_pho, trang_thai) VALUES ('123 Đường A', 'Quận 1', 'TP HCM', 1);
INSERT INTO dia_chi (so_nha, quan_huyen, tinh_thanh_pho, trang_thai) VALUES ('456 Đường B', 'Cầu Giấy', 'Hà Nội', 1);
INSERT INTO dia_chi (so_nha, quan_huyen, tinh_thanh_pho, trang_thai) VALUES ('789 Đường C', 'Hải Châu', 'Đà Nẵng', 1);
INSERT INTO dia_chi (so_nha, quan_huyen, tinh_thanh_pho, trang_thai) VALUES ('321 Đường D', 'Ninh Kiều', 'Cần Thơ', 1);
INSERT INTO dia_chi (so_nha, quan_huyen, tinh_thanh_pho, trang_thai) VALUES ('654 Đường E', 'Hồng Bàng', 'Hải Phòng', 1);

-- 15. HOA_DON
INSERT INTO hoa_don (ma_hoa_don, tong_tien, trang_thai) VALUES ('HD001', 1500000, 'Thành Công');
INSERT INTO hoa_don (ma_hoa_don, tong_tien, trang_thai) VALUES ('HD002', 2000000, 'Chờ Xác Nhận');
INSERT INTO hoa_don (ma_hoa_don, tong_tien, trang_thai) VALUES ('HD003', 500000, 'Đã Hủy');
INSERT INTO hoa_don (ma_hoa_don, tong_tien, trang_thai) VALUES ('HD004', 1200000, 'Đang Giao');
INSERT INTO hoa_don (ma_hoa_don, tong_tien, trang_thai) VALUES ('HD005', 3000000, 'Thành Công');

-- 16. HOA_DON_CHI_TIET
INSERT INTO hoa_don_chi_tiet (gia_ban, so_luong) VALUES (1500000, 1);
INSERT INTO hoa_don_chi_tiet (gia_ban, so_luong) VALUES (1000000, 2);
INSERT INTO hoa_don_chi_tiet (gia_ban, so_luong) VALUES (500000, 1);
INSERT INTO hoa_don_chi_tiet (gia_ban, so_luong) VALUES (600000, 2);
INSERT INTO hoa_don_chi_tiet (gia_ban, so_luong) VALUES (3000000, 1);

-- 17. GIO_HANG
INSERT INTO gio_hang (id_khach_hang, ngay_tao) VALUES (1, CURRENT_TIMESTAMP);
INSERT INTO gio_hang (id_khach_hang, ngay_tao) VALUES (2, CURRENT_TIMESTAMP);
INSERT INTO gio_hang (id_khach_hang, ngay_tao) VALUES (3, CURRENT_TIMESTAMP);
INSERT INTO gio_hang (id_khach_hang, ngay_tao) VALUES (4, CURRENT_TIMESTAMP);
INSERT INTO gio_hang (id_khach_hang, ngay_tao) VALUES (5, CURRENT_TIMESTAMP);

-- 18. GIO_HANG_CHI_TIET
INSERT INTO gio_hang_chi_tiet (so_luong, trang_thai) VALUES (1, 1);
INSERT INTO gio_hang_chi_tiet (so_luong, trang_thai) VALUES (2, 1);
INSERT INTO gio_hang_chi_tiet (so_luong, trang_thai) VALUES (1, 1);
INSERT INTO gio_hang_chi_tiet (so_luong, trang_thai) VALUES (5, 1);
INSERT INTO gio_hang_chi_tiet (so_luong, trang_thai) VALUES (3, 1);

-- 19. CHUC_VU
INSERT INTO chuc_vu (ten, trang_thai) VALUES ('Nhân Viên', 1);
INSERT INTO chuc_vu (ten, trang_thai) VALUES ('Quản Lý', 1);
INSERT INTO chuc_vu (ten, trang_thai) VALUES ('Giám Đốc', 1);
INSERT INTO chuc_vu (ten, trang_thai) VALUES ('Bảo Vệ', 1);
INSERT INTO chuc_vu (ten, trang_thai) VALUES ('Kế Toán', 1);

-- 20. NHAN_VIEN
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, trang_thai) VALUES ('NV001', 'Lý Mạc Sầu', 1);
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, trang_thai) VALUES ('NV002', 'Trương Vô Kỵ', 1);
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, trang_thai) VALUES ('NV003', 'Chu Chỉ Nhược', 1);
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, trang_thai) VALUES ('NV004', 'Triệu Mẫn', 1);
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, trang_thai) VALUES ('NV005', 'Tống Viễn Kiều', 1);

-- 21. VOUCHER
INSERT INTO voucher (ma, ten, gia_tri_tien_mat, trang_thai) VALUES ('V001', 'Giảm 10k', 10000, 1);
INSERT INTO voucher (ma, ten, gia_tri_tien_mat, trang_thai) VALUES ('V002', 'Giảm 20k', 20000, 1);
INSERT INTO voucher (ma, ten, gia_tri_tien_mat, trang_thai) VALUES ('V003', 'Giảm 50k', 50000, 1);
INSERT INTO voucher (ma, ten, gia_tri_tien_mat, trang_thai) VALUES ('V004', 'Giảm 100k', 100000, 1);
INSERT INTO voucher (ma, ten, gia_tri_tien_mat, trang_thai) VALUES ('V005', 'Freeship', 30000, 1);

-- 22. VOUCHER_KHACH_HANG
INSERT INTO voucher_khach_hang (ngay_tao, trang_thai) VALUES (CURRENT_TIMESTAMP, 1);
INSERT INTO voucher_khach_hang (ngay_tao, trang_thai) VALUES (CURRENT_TIMESTAMP, 1);
INSERT INTO voucher_khach_hang (ngay_tao, trang_thai) VALUES (CURRENT_TIMESTAMP, 1);
INSERT INTO voucher_khach_hang (ngay_tao, trang_thai) VALUES (CURRENT_TIMESTAMP, 1);
INSERT INTO voucher_khach_hang (ngay_tao, trang_thai) VALUES (CURRENT_TIMESTAMP, 1);

-- 23. HANG_KHACH_HANG
INSERT INTO hang_khach_hang (ten, diem_toi_thieu) VALUES ('Đồng', 0);
INSERT INTO hang_khach_hang (ten, diem_toi_thieu) VALUES ('Bạc', 1000);
INSERT INTO hang_khach_hang (ten, diem_toi_thieu) VALUES ('Vàng', 5000);
INSERT INTO hang_khach_hang (ten, diem_toi_thieu) VALUES ('Bạch Kim', 10000);
INSERT INTO hang_khach_hang (ten, diem_toi_thieu) VALUES ('Kim Cương', 50000);

-- 24. DON_VI_VAN_CHUYEN
INSERT INTO don_vi_van_chuyen (ten_don_vi, trang_thai) VALUES ('Giao Hàng Nhanh', 1);
INSERT INTO don_vi_van_chuyen (ten_don_vi, trang_thai) VALUES ('Giao Hàng Tiết Kiệm', 1);
INSERT INTO don_vi_van_chuyen (ten_don_vi, trang_thai) VALUES ('Viettel Post', 1);
INSERT INTO don_vi_van_chuyen (ten_don_vi, trang_thai) VALUES ('VNPost', 1);
INSERT INTO don_vi_van_chuyen (ten_don_vi, trang_thai) VALUES ('GrabExpress', 1);

-- 25. HINH_THUC_THANH_TOAN
INSERT INTO hinh_thuc_thanh_toan (hinh_thuc, tien_thanh_toan, trang_thai) VALUES ('Tiền Mặt', 2000000, 1);
INSERT INTO hinh_thuc_thanh_toan (hinh_thuc, tien_thanh_toan, trang_thai) VALUES ('Chuyển Khoản', 1500000, 1);
INSERT INTO hinh_thuc_thanh_toan (hinh_thuc, tien_thanh_toan, trang_thai) VALUES ('Thẻ Tín Dụng', 3000000, 1);
INSERT INTO hinh_thuc_thanh_toan (hinh_thuc, tien_thanh_toan, trang_thai) VALUES ('COD', 500000, 1);
INSERT INTO hinh_thuc_thanh_toan (hinh_thuc, tien_thanh_toan, trang_thai) VALUES ('Ví Điện Tử', 250000, 1);

-- 26. LICH_SU_HOA_DON
INSERT INTO lich_su_hoa_don (hanh_dong, trang_thai_sau_update) VALUES ('Tạo đơn', 'Chờ xác nhận');
INSERT INTO lich_su_hoa_don (hanh_dong, trang_thai_sau_update) VALUES ('Xác nhận', 'Đang giao');
INSERT INTO lich_su_hoa_don (hanh_dong, trang_thai_sau_update) VALUES ('Giao hàng', 'Đang giao');
INSERT INTO lich_su_hoa_don (hanh_dong, trang_thai_sau_update) VALUES ('Hoàn thành', 'Thành công');
INSERT INTO lich_su_hoa_don (hanh_dong, trang_thai_sau_update) VALUES ('Hủy đơn', 'Đã hủy');

-- 27. NOTIFICATION
INSERT INTO notification (title, description) VALUES ('Đơn hàng mới', 'Bạn có đơn hàng mới #1');
INSERT INTO notification (title, description) VALUES ('Khuyến mãi', 'Sale 50% hôm nay');
INSERT INTO notification (title, description) VALUES ('Cập nhật hệ thống', 'Bảo trì lúc 12h');
INSERT INTO notification (title, description) VALUES ('Đơn hàng thành công', 'Đơn #2 đã giao');
INSERT INTO notification (title, description) VALUES ('Hoàn tiền', 'Yêu cầu hoàn tiền #3');

-- 28. QUAN_TRI (Chỉ cần 1 dòng vì bảng này thường là config)
INSERT INTO quan_tri (banner1, title1) VALUES ('banner.jpg', 'Chào mừng đến shop');

-- 29. TAGS
INSERT INTO tags (ten, trang_thai) VALUES ('Mới', 1);
INSERT INTO tags (ten, trang_thai) VALUES ('Hot', 1);
INSERT INTO tags (ten, trang_thai) VALUES ('Sale', 1);
INSERT INTO tags (ten, trang_thai) VALUES ('Limited', 1);
INSERT INTO tags (ten, trang_thai) VALUES ('Trend', 1);

-- 30. TAGS_SAN_PHAM
INSERT INTO tags_san_pham (id_tag, id_san_pham) VALUES (1, 1);
INSERT INTO tags_san_pham (id_tag, id_san_pham) VALUES (2, 2);
INSERT INTO tags_san_pham (id_tag, id_san_pham) VALUES (3, 3);
INSERT INTO tags_san_pham (id_tag, id_san_pham) VALUES (4, 4);
INSERT INTO tags_san_pham (id_tag, id_san_pham) VALUES (5, 5);

COMMIT;